//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.straw.friend.bean;

import android.content.Context;

public final class User_
    extends User
{

    private Context context_;

    private User_(Context context) {
        context_ = context;
        init_();
    }

    public static User_ getInstance_(Context context) {
        return new User_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
