//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.straw.friend.service;

import android.content.Context;
import com.straw.friend.MyApplication_;
import org.androidannotations.api.builder.ServiceIntentBuilder;

public final class GpsService_
    extends GpsService
{


    public static GpsService_.IntentBuilder_ intent(Context context) {
        return new GpsService_.IntentBuilder_(context);
    }

    private void init_() {
        application = MyApplication_.getInstance();
        init();
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

    public static class IntentBuilder_
        extends ServiceIntentBuilder<GpsService_.IntentBuilder_>
    {


        public IntentBuilder_(Context context) {
            super(context, GpsService_.class);
        }

    }

}
