package com.straw.friend.bean;

import java.util.Date;

import org.androidannotations.annotations.EBean;
@EBean
public class CircleUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_user.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_user.circleid
     *
     * @mbggenerated
     */
    private String circleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_user.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_user.createDate
     *
     * @mbggenerated
     */
    private long createdate;
    private String content;
    
    public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_user.Id
     *
     * @return the value of circle_user.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_user.Id
     *
     * @param id the value for circle_user.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_user.circleid
     *
     * @return the value of circle_user.circleid
     *
     * @mbggenerated
     */
    public String getCircleid() {
        return circleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_user.circleid
     *
     * @param circleid the value for circle_user.circleid
     *
     * @mbggenerated
     */
    public void setCircleid(String circleid) {
        this.circleid = circleid == null ? null : circleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_user.userid
     *
     * @return the value of circle_user.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_user.userid
     *
     * @param userid the value for circle_user.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

	public long getCreatedate() {
		return createdate;
	}

	public void setCreatedate(long createdate) {
		this.createdate = createdate;
	}
    
} 