package com.straw.friend.bean;

import java.util.Date;
import java.util.UUID;

public class Joke {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joke.id
     *
     * @mbggenerated
     */
    private String id = UUID.randomUUID().toString();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joke.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joke.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joke.createDate
     *
     * @mbggenerated
     */
    private long createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joke.id
     *
     * @return the value of joke.id
     *
     * @mbggenerated
     */
    private String userid;
    
    public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joke.id
     *
     * @param id the value for joke.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joke.title
     *
     * @return the value of joke.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joke.title
     *
     * @param title the value for joke.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joke.content
     *
     * @return the value of joke.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joke.content
     *
     * @param content the value for joke.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

	public long getCreatedate() {
		return createdate;
	}

	public void setCreatedate(long createdate) {
		this.createdate = createdate;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joke.createDate
     *
     * @return the value of joke.createDate
     *
     * @mbggenerated
     */
    
}